imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    # exception_controller:  AppBundle:Exception:showException
    globals:
        parameters_config_prices: %parameters_config_prices%
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['AppBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jpegoptim:
            bin: /usr/bin/jpegoptim
            max: 70
            apply_to: "\.jpe?g$"
            strip_all: true
    twig:
        functions:
            jpegoptim: { output: %kernel.root_dir%/web/assets/img/*.jpg }
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Doctrine Extensions
stof_doctrine_extensions:
    default_locale: ru_RU
    orm:
        default:
            timestampable: true

#FOSUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    group:
        group_class: UserBundle\Entity\Group

#LiipImagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        main_slider:
            quality: 90
            filters:
                thumbnail: { size: [1900, 585], mode: outbound }
        clouds_slider:
            quality: 90
            filters:
                thumbnail: { size: [1900, 66], mode: outbound }
        portfolio_slider:
            quality: 60
            filters:
                thumbnail: { size: [1170, 580], mode: outbound }
        article_preview_all:
            quality: 90
            filters:
                thumbnail: { size: [300, 242], mode: outbound }
        article_preview:
            quality: 90
            filters:
                thumbnail: { size: [340, 272], mode: outbound }
        article_show:
            quality: 90
            filters:
                thumbnail: { size: [885, 410], mode: outbound }
        module_preview_all:
            quality: 90
            filters:
                thumbnail: { size: [300, 242], mode: outbound }
        module_preview_modal:
            quality: 90
            filters:
                thumbnail: { size: [300, 242], mode: outbound }
# Pagination
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AppBundle:Pagination:sliding.html.twig
        sortable: AppBundle:Pagination:sortable_link.html.twig # sort link template

#TinyMCE
#stfalcon_tinymce:
#    include_jquery: false
#    tinymce_jquery: true
#    language: ru
#    theme:
#        advanced:
#            plugins:
#             - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
#             - "searchreplace wordcount visualblocks visualchars code fullscreen"
#             - "insertdatetime media nonbreaking save table contextmenu directionality"
#             - "emoticons template paste textcolor"
#            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
#            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
#Genemu form
genemu_form:
    date: ~
    # image: ~
    tinymce:
        enabled: false
    autocomplete: ~
    select2:
        enabled: true
        configs:
            placeholder: Выберете значение
            width: 550
            allowClear: false
            minimumInputLength: 0

# KNP Snappy
knp_snappy:
    pdf:
        enabled:    true
#        binary:     /usr/bin/wkhtmltopdf-amd64
        binary:     /usr/bin/wkhtmltopdf
        options:    []
#    image:
#        enabled:    true
#        binary:     /usr/bin/wkhtmltoimage
#        options:    []